name: Build & Upload Standalone Artifact

on:
  workflow_dispatch:
    inputs:
      artifact_tag:
        description: 'Tag name to build the artifact from (e.g., 0.0.3). This tag must exist in the trading repository.'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Trading Repository at Provided Tag
        uses: actions/checkout@v4
        with:
          repository: trading-cz/trading
          ref: ${{ github.event.inputs.artifact_tag }}
          token: ${{ secrets.TRADING_PAT }}
          path: trading

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Parse Tag and Prepare Build
        working-directory: trading
        run: |
          # Use the provided tag as the version number.
          VERSION="${{ github.event.inputs.artifact_tag }}"
          echo "Using artifact version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Standalone Artifact with PyInstaller
        working-directory: trading
        run: |
          # Clean any previous PyInstaller artifacts.
          rm -rf build dist *.spec

          # Install application dependencies and PyInstaller.
          pip install --upgrade --no-cache-dir -r requirements.txt
          pip install pyinstaller

          # Build the standalone executable.
          # The --onefile option creates a single-file bundle.
          # The --name option names the executable with the version.
          pyinstaller --onefile --name trading-${VERSION} __main__.py

          # Copy symbols.txt from data/ into dist so it sits next to the executable.
          cp data/symbols.txt dist/symbols.txt

          # List the contents of the dist folder for verification.
          ls -l dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          # This will upload the entire "dist" folder, which now contains both files.
          name: "trading-${{ env.VERSION }}"
          path: "trading/dist"
