name: Build & Upload Zipapp Artifact

on:
  workflow_dispatch:
    inputs:
      artifact_tag:
        description: 'Tag name to build the artifact from (e.g., 0.0.3). This tag must exist in the trading repository.'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Trading Repository at Provided Tag
        uses: actions/checkout@v4
        with:
          repository: trading-cz/trading
          ref: ${{ github.event.inputs.artifact_tag }}
          # Use a PAT with permissions to access the trading repository.
          token: ${{ secrets.TRADING_PAT }}
          path: trading

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Parse Tag and Prepare Build
        working-directory: trading
        run: |
          # The provided tag is used as the version.
          VERSION="${{ github.event.inputs.artifact_tag }}"
          echo "Using artifact version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Zipapp Artifact
        working-directory: trading
        run: |
          # Remove any previous build folder and create a fresh build directory.
          rm -rf build && mkdir build

          # Install dependencies from requirements.txt into the build folder.
          pip install --upgrade --no-cache-dir -r requirements.txt --target build

          # Copy the entry point (__main__.py) and the inner source folder.
          cp __main__.py build/
          cp -r trading/ build/trading

          # Copy the data folder if it exists.
          if [ -d data ]; then
            cp -r data build/data
          fi

          # Build the zipapp. The bundled __main__.py acts as the entry point.
          python -m zipapp build -o trading-${VERSION}.pyz

          # List the produced file for verification.
          ls -l

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          # Artifact is named without invalid characters.
          name: "trading-${{ env.VERSION }}"
          path: "trading/trading-${{ env.VERSION }}.pyz"
