name: Hetzner Kafka Deployment

on:
  workflow_dispatch:
    inputs:
      server_name:
        description: 'Name for the Hetzner server'
        required: true
        default: 'kafka-server'
      server_type:
        description: 'Hetzner server type'
        required: true
        default: 'cx22'
      image:
        description: 'Server image'
        required: true
        default: 'ubuntu-24.04'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get install -y sshpass
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "All dependencies installed successfully"
  
      - name: Create Server
        id: create-server
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
          HCLOUD_SERVER_NAME: ${{ inputs.server_name }}
          HCLOUD_SERVER_TYPE: ${{ inputs.server_type }}
          HCLOUD_IMAGE: ${{ inputs.image }}
        run: |
          echo "Creating server with name: $HCLOUD_SERVER_NAME, type: $HCLOUD_SERVER_TYPE, image: $HCLOUD_IMAGE"
          # Execute the create_server script and capture its output variables
          python scripts/hetzner/create_server.py | grep -E "^SERVER_IP=|^ROOT_PASS=" >> $GITHUB_OUTPUT
          echo "Server creation completed"

      - name: Install Kafka
        env:
          SERVER_IP: ${{ steps.create-server.outputs.SERVER_IP }}
          ROOT_PASS: ${{ steps.create-server.outputs.ROOT_PASS }}
        run: |
          echo "Starting Kafka installation on server $SERVER_IP"
          ls -la config/kafka/
          chmod +x scripts/kafka/install_kafka.sh
          ./scripts/kafka/install_kafka.sh $SERVER_IP "$ROOT_PASS"
          echo "Kafka installation completed"
      
      - name: Verify Kafka Installation
        env:
          SERVER_IP: ${{ steps.create-server.outputs.SERVER_IP }}
          ROOT_PASS: ${{ steps.create-server.outputs.ROOT_PASS }}
        run: |
          echo "Verifying Kafka installation on server $SERVER_IP"
          chmod +x scripts/kafka/verify_kafka.sh
          ./scripts/kafka/verify_kafka.sh $SERVER_IP "$ROOT_PASS"
          echo "Kafka verification completed"
      
      - name: Save credentials securely
        env:
          ROOT_PASS: ${{ steps.create-server.outputs.ROOT_PASS }}
        run: |
          echo "$ROOT_PASS" > server_password.txt
          
      - name: Upload server credentials
        uses: actions/upload-artifact@v4
        with:
          name: server-credentials
          path: server_password.txt
          retention-days: 1
          
      - name: Post deployment message
        run: |
          echo "Kafka successfully deployed to server ${{ steps.create-server.outputs.SERVER_IP }}"
          echo "Server details:"
          echo "  - IP Address: ${{ steps.create-server.outputs.SERVER_IP }}"
          echo "  - Server Name: ${{ inputs.server_name }}"
          echo "  - Server Type: ${{ inputs.server_type }}"
          echo "You can connect to the server with: ssh root@${{ steps.create-server.outputs.SERVER_IP }}"
          echo "The server password has been saved as a GitHub artifact named 'server-credentials'"
          echo "Download it from the Actions tab in your repository"
