name: Kafka Installation

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: 'Server IP address'
        required: true
      ssh_private_key:
        description: 'SSH private key for server access (raw or base64 encoded)'
        required: true
        type: string

jobs:
  install-kafka:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          
          # Write the key with proper line breaks
          # First save to a temporary file to avoid showing key in logs
          cat > ~/.ssh/id_hetzner << 'EOT'
          ${{ inputs.ssh_private_key }}
          EOT
          
          # Set proper permissions
          chmod 600 ~/.ssh/id_hetzner
          
          # Add server to known hosts
          ssh-keyscan -H ${{ inputs.server_ip }} >> ~/.ssh/known_hosts
          
          # Validate the key - this will show if it's valid without revealing content
          if ssh-keygen -l -f ~/.ssh/id_hetzner &> /dev/null; then
            echo "✅ SSH key is valid"
          else
            echo "❌ SSH key appears to be invalid or in wrong format"
            echo "Attempting to fix key format..."
            
            # Sometimes keys need proper line breaks - let's ensure they're present
            sed -i 's/\\n/\n/g' ~/.ssh/id_hetzner
            
            # Check again
            if ssh-keygen -l -f ~/.ssh/id_hetzner &> /dev/null; then
              echo "✅ SSH key fixed and is now valid"
            else
              echo "❌ Still unable to read the SSH key. Please verify the provided key."
              exit 1
            fi
          fi
          
          # Test connection
          echo "Testing SSH connection..."
          if ssh -o StrictHostKeyChecking=no -o BatchMode=yes -i ~/.ssh/id_hetzner root@${{ inputs.server_ip }} "echo 'SSH connection successful'"; then
            echo "✅ SSH connection test successful"
          else
            echo "❌ SSH connection test failed"
            exit 1
          fi
  
      - name: Install Kafka
        env:
          SERVER_IP: ${{ inputs.server_ip }}
          SSH_KEY_PATH: ~/.ssh/id_hetzner
        run: |
          echo "Starting Kafka installation on server $SERVER_IP"
          ls -la config/kafka/
          chmod +x scripts/kafka/install_kafka.sh
          ./scripts/kafka/install_kafka.sh $SERVER_IP "$SSH_KEY_PATH"
          echo "Kafka installation completed"
      
      - name: Verify Kafka Installation
        env:
          SERVER_IP: ${{ inputs.server_ip }}
          SSH_KEY_PATH: ~/.ssh/id_hetzner
        run: |
          echo "Verifying Kafka installation on server $SERVER_IP"
          chmod +x scripts/kafka/verify_kafka.sh
          ./scripts/kafka/verify_kafka.sh $SERVER_IP "$SSH_KEY_PATH"
          echo "Kafka verification completed"
          
      - name: Post installation message
        run: |
          echo "Kafka successfully deployed to server ${{ inputs.server_ip }}"
          echo "You can connect to the server with: ssh -i your_private_key root@${{ inputs.server_ip }}"
