name: Kafka Installation

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: 'Server IP address'
        required: true
      ssh_private_key:
        description: 'SSH private key for server access (raw or base64 encoded)'
        required: true
        type: string

jobs:
  install-kafka:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          
          # Check if the key looks like base64 (only contains base64 characters and is 1+ lines)
          if [[ "${{ inputs.ssh_private_key }}" =~ ^[A-Za-z0-9+/=[:space:]]*$ && ! "${{ inputs.ssh_private_key }}" =~ -----BEGIN ]]; then
            # It's base64 encoded - decode it
            echo "Key appears to be base64 encoded, decoding..."
            echo "${{ inputs.ssh_private_key }}" | base64 -d > ~/.ssh/id_hetzner
          else
            # It's raw - use directly
            echo "Key appears to be raw, using directly..."
            echo "${{ inputs.ssh_private_key }}" > ~/.ssh/id_hetzner
          fi
          
          chmod 600 ~/.ssh/id_hetzner
          ssh-keyscan -H ${{ inputs.server_ip }} >> ~/.ssh/known_hosts
          
          # Debug info (without revealing the key)
          ls -la ~/.ssh/id_hetzner
          echo "SSH key size: $(wc -c < ~/.ssh/id_hetzner) bytes"
  
      - name: Install Kafka
        env:
          SERVER_IP: ${{ inputs.server_ip }}
          SSH_KEY_PATH: ~/.ssh/id_hetzner
        run: |
          echo "Starting Kafka installation on server $SERVER_IP"
          ls -la config/kafka/
          chmod +x scripts/kafka/install_kafka.sh
          ./scripts/kafka/install_kafka.sh $SERVER_IP "$SSH_KEY_PATH"
          echo "Kafka installation completed"
      
      - name: Verify Kafka Installation
        env:
          SERVER_IP: ${{ inputs.server_ip }}
          SSH_KEY_PATH: ~/.ssh/id_hetzner
        run: |
          echo "Verifying Kafka installation on server $SERVER_IP"
          chmod +x scripts/kafka/verify_kafka.sh
          ./scripts/kafka/verify_kafka.sh $SERVER_IP "$SSH_KEY_PATH"
          echo "Kafka verification completed"
          
      - name: Post installation message
        run: |
          echo "Kafka successfully deployed to server ${{ inputs.server_ip }}"
          echo "You can connect to the server with: ssh -i your_private_key root@${{ inputs.server_ip }}"
