name: Kafka Installation

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: 'Server IP address'
        required: true

jobs:
  install-kafka:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Set up SSH access using webfactory/ssh-agent
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add server to known hosts
        run: ssh-keyscan -H ${{ inputs.server_ip }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no root@${{ inputs.server_ip }} "echo 'SSH connection successful'"

      - name: Install Kafka
        run: |
          echo "Starting Kafka installation on server ${{ inputs.server_ip }}"
          ls -la config/kafka/
          chmod +x scripts/kafka/install_kafka.sh
          ./scripts/kafka/install_kafka.sh ${{ inputs.server_ip }}
          echo "Kafka installation completed"
      
      - name: Verify Kafka Installation
        run: |
          echo "Verifying Kafka installation on server ${{ inputs.server_ip }}"
          chmod +x scripts/kafka/verify_kafka.sh
          ./scripts/kafka/verify_kafka.sh ${{ inputs.server_ip }}
          echo "Kafka verification completed"
          
      - name: Post installation message
        run: |
          echo "Kafka successfully deployed to server ${{ inputs.server_ip }}"
          echo "You can connect to the server with: ssh -i your_private_key root@${{ inputs.server_ip }}"
